name: caravansary
description: Flutter app about spices and herbs

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: 4.0.4
  get_it: 4.0.1

  flutter:
    sdk: flutter

  cupertino_icons: 0.1.3

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  pedantic: 1.9.0
flutter:
  uses-material-design: true
