name: caravansary
description: Flutter app about spices and herbs

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  spices_herbs:
    path: modules/spices_herbs
  blends:
    path: modules/blends
  recipes:
    path: modules/recipes
  settings:
    path: modules/settings
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.9.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  pedantic: 1.9.0
flutter:
  uses-material-design: true
