name: Basic

on: push

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1

      - run: flutter doctor

      - run: flutter format -l 120 -n --set-exit-if-changed ./lib

      - run: flutter analyze

      - run: flutter test